# rvm
source "http://rubygems.org"

# in each ruby
# gem install bundler
# remove other versions of rake
gem 'rake', '0.8.7'
# rvm install rubygems 1.3.7
gem 'terminitor'
gem 'hudson', :git => "git@github.com:bf4/hudson.rb.git"
gem 'clockwork'
gem 'grit'
# bundle install
